forum/urls.py
from django.conf.urls import url
from .views import index, add_message, dashboard, clear
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_message/(?P<id>.*)/$', add_message, name='add_message'),
	url(r'^dashboard/$', dashboard, name='dashboard'),

	url(r'^clear/(?P<object_id>[0-9]+)', view=clear, name='clear'),

	# custom auth
	url(r'^custom_auth/login/$', auth_login, name='auth_login'),
	url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

tp2/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import Tugas2.urls as Tugas2
import app_profile.urls as app_profile
import forum.urls as forum
import login_linkedln.urls as login_linkedln
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tugas2/',include(Tugas2,namespace='Tugas2')),
    url(r'^profile/',include(app_profile,namespace='profile')),
   	url(r'^forum/',include(forum,namespace='forum')),
	url(r'^login/',include(login_linkedln,namespace='login_linkedln')),
    url(r'^$',RedirectView.as_view(url='/login/',permanent = True), name='goto-login'),



]

forum/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    nama = models.CharField('Nama', max_length=200)
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Message(models.Model):
	user = models.ForeignKey(User)
	title = models.CharField(max_length=140)
	message = models.TextField()
	kode_message = models.CharField("Kode Message", max_length=50)
	created_date = models.DateTimeField(auto_now_add=True)

forum/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    title_attrs = {
        'class': 'form-control',
        'placeholder':'Post About'
    }

    message_attrs = {
        'class': 'form-control',
        'placeholder':'Your Post'
    }

    title = forms.CharField(label='Title', required=True, max_length=30, widget=forms.TextInput(attrs=title_attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=message_attrs), required=True)

forum/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import Message_Form
from .models import Message
from .utils import *

# Create your views here.
response = {}
def index(request):
    # print ("#==> masuk index")
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('forum:dashboard'))
    else:
        response['author'] = get_data_user(request, 'user_login')
        html = 'forum/login.html'
        return render(request, html, response)

def dashboard(request):

    if not 'user_login' in request.session.keys():
        return HttpResponseRedirect(reverse('forum:index'))
    else:
        kode_identitas = get_data_user(request, 'kode_identitas')
        try:
            user = User.objects.get(kode_identitas = kode_identitas)
        except Exception as e:
            user = create_new_user(request)

        message = Message.objects.filter(user=user)

        response['message'] = message
        response['message_form'] = Message_Form
        response["message_list"] = message
        html = 'forum/forum.html'

        message_list = message
        paginator = Paginator(message_list, 5)
        page = request.GET.get('page', 1)
        try:
            users = paginator.page(page)
        except PageNotAnInteger:
            users = paginator.page(1)
        except EmptyPage:
            users = paginator.page(paginator.num_pages)

        response["message_list"] = users
        html = 'forum/forum.html'
        return render(request, html, response)

def add_message(request, id):
    response['id'] = id
    form = Message_Form(request.POST or None)

    if (request.method == 'POST' and form.is_valid()):
        kode_identitas = get_data_user(request, 'kode_identitas')
        try:
            user = User.objects.get(kode_identitas = kode_identitas)
        except Exception as e:
            user = create_new_user(request)

        response['title'] = request.POST['title']
        response['message'] = request.POST['message']
        message = Message(user=user,title=response['title'], message=response['message'], kode_message = id)
        message.save()
        response['id'] = id
        html ='forum/forum.html'
        return HttpResponseRedirect('/forum/')

def clear(request,object_id):
    clears = Message.objects.get(pk=object_id)
    clears.delete()
    return HttpResponseRedirect('/forum/')

forum/templates/forum/forum.html
{% extends "forum/layout/base.html" %}

{% load staticfiles %}
{% load static %}

{% block header %}
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
    </div>
    <div align="center">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/profile/">Profile</a></li>
        <li class="active"><a href="forum">Forum</a></li>
        <li><a href="{% url 'forum:auth_logout' %}" class="btn btn-default navbar-btn" onclick="return confirm('Processing Logout?')"><img src="https://png.icons8.com/exit/androidL/50/000000" style="width: 25px;height 25px">Logout </a></li>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class="container-fluid big-logo-row">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 big-logo-container">
        <h1 class="big-logo">LingIn</h1>
      </div><!--/.col-xs-12 -->
    </div><!--/.row -->
  </div><!--/.container -->
</div><!--/.container-fluid -->
{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid text-center" style="margin-bottom: 0px; margin-top: 0px; background-color: #F1F7ED">
  <div class="container">
    <h1 class="display-3" style="font-family: Impact;">Forum Diskusi Lowongan</h1>
    <h4 class="lead" style="fontfamily: Impact">Join and Be Our Team</h4>
  </div>
</div>

{% if message_list %}
{% for data in message_list %}
  <section name="update-forum" id="update-forum">
      <div class = "status">
          <div class="row">
              <div class="col-sm-12 col-sm-offset-0">
                <div class="media" style="padding: 15px">
                  <div class="media-body">
                      <strong>{{data.title}}</strong>
                      <div class="delete" data-id="{{data.id}}">
                        <a href="{% url 'forum:clear' object_id=data.id %}"><img src="https://png.icons8.com/trash/win8/50/000000" style="width: 25px;height 25px; top: 10px;"></a>
                      </div>
                      <h6>Posted on {{data.created_date}}</h6>
                      <p>{{data.message}}</p>
                  </div>
                </section>
                  </div>
                </div>
              </div>
{% endfor %}
{% else %}
    <button type="submit" class="btn btn-primary btn-lg btn-block no-friend">You have no discussion.</button>
{% endif %}

{% if message_list.has_other_pages %}
  <div class="text-center">
    <ul class="pagination">
        {% if message_list.has_previous %}
            <li><a href="?page={{ message_list.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        {% for i in message_list.paginator.page_range %}
            {% if message_list.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if message_list.has_next %}
              <li><a href="?page={{ message_list.next_page_number }}">&raquo;</a></li>
        {% else %}
              <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
  </div>
{% endif %}

<section name="form">
    <h3>Tambah Lowongan</h3>
    <form id="form" method="POST" action="{% url 'forum:add_message' id %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-primary">Post</button>
    </form>
</section>
{% endblock %}

forum/templates/forum/login.html
{% extends "forum/layout/base.html" %}

{% block header %}
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
    </div>
  </div>
</div>

<div class="container-fluid big-logo-row">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 big-logo-container">
        <h1 class="big-logo">LingIn</h1>
      </div><!--/.col-xs-12 -->
    </div><!--/.row -->
  </div><!--/.container -->
</div><!--/.container-fluid -->
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'forum:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}